### ISSUE TITLE
different name of instance resulting in server not found

### ISSUE THREAD

**Issue by andreimihaivadan** [owncloud/OwncloudUniversal#15]
My server instance is named for example ownCloud, but when the app is checking the status, it makes in Owncloud\OssClient.cs  in _BuildStatusUrl (string input) , input.TrimEnd('/').toLower(); wich makes the app unusable;
A user can name his instance however it want's so it's incorrect in searching for owncloud.

**Comment by pestotoast** [comment]
Fixed with #16
