### ISSUE TITLE
Failing to sync Camera Roll

### ISSUE THREAD

**Issue by phalouvas** [owncloud/OwncloudUniversal#17]
In Windows mobile 950 it fails to sync folder Pictures/Camera Roll. This is the folder where Camera save the pictures. I also tried to reproduce it on a Windows 10 desktop, and surface but failed. I suppose that's because on mobile is missing the legacy binaries, and try to read changes from Search Index.

It's obvious that the problem lies on OwncloudUniversal.Synchronization.LocalFileSystem.FileSystemAdapter function _GetChangesFromSearchIndex

It seems an obvious solution to also get files directly from StorageFolder when the specific folder. Let me know if you need more clarifications.

**Comment by pestotoast** [comment]
Is your Camera Roll Folder on the internal storage or on the external sd card? It works fine on my phone but I only have a Lumia 930 which has no external sd-card.
I don't think Windows Mobile is missing any libraries - it has the Search Indexer built in too and Microsoft does recommend this when enumerating large folders.

**Comment by phalouvas** [comment]
I tested it on both internal and external. They both failed if the camera is 'locked' on the corresponding card. For example if I have the camera to save on internal, then it does not track changes on the internal, but is ok on SD, and vice versa. All other folders, except the "Camera Roll" track all the changes.

It can download without any problem, but it does not track anything on the local (add, modify, delete) It seems like the search indexer does not track the changes, but it does read the files.

**Comment by pestotoast** [comment]
I have added a workaround for this issue. Can you test (with demo files) if this works for you? 
You can find the modified package for sideloading here: https://ci.appveyor.com/project/DeepDiver1975/ownclouduniversal/build/1.0.180/artifacts

Please keep in mind that this is a development version of the app which should only be used for testing.

**Comment by phalouvas** [comment]
It seems to be ok now. Should you add this change in store so I uninstall the test version from my Phone?

**Comment by pestotoast** [comment]
Yes, I will do that. But I don't know yet when the update will be ready for the store. There are still some other things I have to finish first.

**Comment by phalouvas** [comment]
ok, thanks!!!
