### ISSUE TITLE
Integrate an option to trust self-signed certificates

### ISSUE THREAD

**Issue by chaehni** [owncloud/OwncloudUniversal#18]
It would be great if users were able to trust self-signed certificates as many are hosting the ownCloud instance on their own hardware. Desktop and mobile clients already offer this option.

**Comment by michaelstingl** [comment]
Not all features in oC iOS and Android app work with self-signed cert. (video streaming for example). You need to add your cert to the system using profiles as a workaround.

On the other hand, Let's Encrypt certificates are free now, and with Let's Encrypt planning to have wildcard certs as well, there are really limited us cases for self-signed certs.

**Comment by pestotoast** [comment]
I agree with you @michaelstingl but this requirement comes up frequently. @chaehni  There only is a workaround at the moment: 
- Export the certificate with chrome or firefox into a p7b-file. 
- Open that file on the phone. (On Windows Desktops you have to add the certificate to the trustet root certificate store.) 
- Once the certificate is installed you don't get a warning when you access oC with your browser and you can use the app without limitations

I can programmatically ignore certificate errors for HTTP-requests to the server. But for uploads and downloads of files I use the Background-Transfer-Api of Windows which allows the completion of long transfers even when the app is in standby (or automatic restarts if there are connection issues). 
But with this background-api I don't create the server requests myself - so I can't ignore certificate errors.

If we want to allow self signed certs we can't use that functionality. (The might be more limitations which I can't remember at the moment, but I think video streaming and displaying pictures should work).

**Comment by chaehni** [comment]
Thanks @pestotoast for the clarification. I'm aware of this workaround. It's just that most users aren't. I was not aware that the API doesn't allow this. This makes a lot more sense now. However, many other UWP cloud storage apps seem to support this. I'll have to look how they handle file transfers, then.

**Comment by pestotoast** [comment]
There was more feedback via store reviews so I decided to add this. I removed all usages of the Background-Transfer-Api and added support for self signed certificates.
When the user tries to set up a server with a self signed certificate he will have to verify the fingerprint and then the certificate will be installed on the device.
